{
 "title": "Taxi Data Model",
 "time": { "from": "2022-01-29T01:37:22.259Z", "to": "2022-02-27T21:26:49.184Z" },
 "panels": [
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", prediction_drift FROM taxi_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", num_drifted_columns FROM taxi_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Missing Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", share_missing_values FROM taxi_metrics LIMIT 50 "
    }
   ]
  }
 ]
}